/*
 * Demo data used by seedData.js: 2 recruiters, their companies, 8 jobs each.
 *
 * Job descriptions are written as a list of lines joined with "\n".
 * The job details page shows each line on its own row, and job cards
 * show only the first two lines, so the first line is a short summary.
 */

export const owners = [
    {
        user: {
            fullname: "Ananya Sharma",
            email: "ananya.hr@example.com",
            phoneNumber: 9876543210,
        },
        company: {
            name: "TechNova Solutions",
            description: "A product company building web and mobile apps for startups and enterprises.",
            website: "https://technova.example.com",
            location: "Bangalore",
        },
        jobs: [
            {
                title: "Senior Frontend Developer",
                description: [
                    "TechNova Solutions is looking for a Senior Frontend Developer to lead the frontend team and build fast, accessible React interfaces for our main product. You will own the frontend architecture, set coding standards and help grow a team of five developers.",
                    "",
                    "What you'll do:",
                    "• Design and build complex, reusable React components used across our web apps",
                    "• Make key decisions on state management, performance and frontend architecture",
                    "• Review pull requests and mentor junior and mid-level developers",
                    "• Work closely with designers and backend engineers to plan and ship new features",
                    "• Improve page speed, accessibility (WCAG) and test coverage",
                    "",
                    "What we offer:",
                    "• Competitive salary with a yearly performance bonus",
                    "• Health insurance for you and your family",
                    "• Flexible working hours and 2 days of work from home every week",
                    "• Yearly learning budget for courses and conferences",
                ].join("\n"),
                requirements: ["React", "TypeScript", "Redux", "5+ years of frontend experience", "Code reviews and mentoring"],
                salary: "25-35 LPA",
                location: "Bangalore",
                jobType: "Full Time",
                experienceLevel: "Senior",
                position: 2,
            },
            {
                title: "Frontend Developer Intern",
                description: [
                    "Start your career in web development with a 6-month remote internship at TechNova Solutions. You will learn frontend development by building real features with React and Tailwind CSS, guided by a dedicated mentor from our team.",
                    "",
                    "What you'll do:",
                    "• Build UI components and pages from Figma designs",
                    "• Fix bugs and small issues in our live web apps",
                    "• Write clean, readable code and learn how code reviews work",
                    "• Join daily stand-ups and weekly learning sessions with the team",
                    "",
                    "What we offer:",
                    "• Monthly stipend and a fully remote setup",
                    "• One-on-one mentorship from a senior developer",
                    "• Internship certificate and a letter of recommendation",
                    "• Chance of a full-time offer based on performance",
                ].join("\n"),
                requirements: ["HTML", "CSS", "JavaScript basics", "Some React knowledge", "Willing to learn"],
                salary: "3-4 LPA",
                location: "Remote",
                jobType: "Internship",
                experienceLevel: "Fresher",
                position: 3,
            },
            {
                title: "Backend Developer (Node.js)",
                description: [
                    "Join our backend team to design and build the REST APIs that power TechNova's web and mobile apps. You will work with Node.js, Express and MongoDB on services used by thousands of people every day.",
                    "",
                    "What you'll do:",
                    "• Design, build and document REST APIs with Node.js and Express",
                    "• Model data in MongoDB and write fast, well-indexed queries",
                    "• Add secure login and permissions with JWT",
                    "• Write unit and integration tests and fix issues in production",
                    "• Work with frontend and mobile developers to plan new features",
                    "",
                    "What we offer:",
                    "• Competitive salary and a yearly bonus",
                    "• Health insurance and paid sick leave",
                    "• Hybrid work: 3 days in the office, 2 days from home",
                    "• A new laptop and a yearly learning budget",
                ].join("\n"),
                requirements: ["Node.js", "Express.js", "MongoDB", "REST API design", "JWT authentication"],
                salary: "15-22 LPA",
                location: "Bangalore",
                jobType: "Full Time",
                experienceLevel: "Mid-Level",
                position: 2,
            },
            {
                title: "Full Stack Developer (MERN)",
                description: [
                    "We are hiring a Full Stack Developer to work on both the frontend and backend of our client projects using the MERN stack. This is a great role for developers with 1-3 years of experience who want to grow quickly across the whole stack.",
                    "",
                    "What you'll do:",
                    "• Build features end to end with React, Node.js, Express and MongoDB",
                    "• Turn designs into responsive, working pages",
                    "• Connect the frontend to REST APIs and handle errors and loading states",
                    "• Deploy apps and fix bugs reported by clients",
                    "• Take part in sprint planning and code reviews",
                    "",
                    "What we offer:",
                    "• A clear growth path to Mid-Level Developer",
                    "• Health insurance",
                    "• A friendly team and weekly knowledge-sharing sessions",
                    "• Flexible working hours",
                ].join("\n"),
                requirements: ["MongoDB", "Express.js", "React", "Node.js", "Git"],
                salary: "8-12 LPA",
                location: "Pune",
                jobType: "Full Time",
                experienceLevel: "Junior",
                position: 3,
            },
            {
                title: "UI/UX Designer",
                description: [
                    "TechNova Solutions is looking for a UI/UX Designer to design clean, user-friendly screens for our web and mobile apps. You will own the design process from user research and wireframes all the way to polished final designs.",
                    "",
                    "What you'll do:",
                    "• Talk to users and turn their problems into clear design solutions",
                    "• Create wireframes, user flows and clickable prototypes in Figma",
                    "• Design final screens for web and mobile that follow our design system",
                    "• Work closely with developers to make sure designs are built correctly",
                    "• Run usability tests and improve designs based on feedback",
                    "",
                    "What we offer:",
                    "• Competitive salary and a yearly bonus",
                    "• Health insurance",
                    "• Budget for design tools, books and courses",
                    "• Hybrid work from our Mumbai office",
                ].join("\n"),
                requirements: ["Figma", "Wireframing", "Prototyping", "User research", "A strong portfolio"],
                salary: "12-18 LPA",
                location: "Mumbai",
                jobType: "Full Time",
                experienceLevel: "Mid-Level",
                position: 1,
            },
            {
                title: "UI/UX Design Intern",
                description: [
                    "Our design team is looking for a UI/UX Design Intern for a 6-month remote internship. You will help create wireframes, mockups and design systems for new features and learn how real products are designed.",
                    "",
                    "What you'll do:",
                    "• Create wireframes and mockups in Figma with help from senior designers",
                    "• Help keep our design system (colors, fonts, components) up to date",
                    "• Join user research calls and take notes",
                    "• Present your designs to the team and improve them based on feedback",
                    "",
                    "What we offer:",
                    "• Monthly stipend and a fully remote setup",
                    "• Weekly one-on-one sessions with a senior designer",
                    "• Real projects you can add to your portfolio",
                    "• Internship certificate and a chance of a full-time offer",
                ].join("\n"),
                requirements: ["Figma basics", "Interest in design", "Good communication"],
                salary: "2-3 LPA",
                location: "Remote",
                jobType: "Internship",
                experienceLevel: "Fresher",
                position: 2,
            },
            {
                title: "React Native Developer",
                description: [
                    "We need a React Native Developer on a 6-month contract to build and ship cross-platform mobile apps for Android and iOS. You will work on a new mobile app for one of our biggest clients, from the first screen to the app store release.",
                    "",
                    "What you'll do:",
                    "• Build mobile screens and features with React Native",
                    "• Connect the app to our REST APIs and handle poor or no internet connection",
                    "• Add push notifications, image uploads and in-app navigation",
                    "• Test the app on real Android and iOS devices and fix bugs",
                    "• Help publish the app on the Google Play Store and Apple App Store",
                    "",
                    "What we offer:",
                    "• Good monthly contract pay",
                    "• Option to extend the contract or move to a full-time role",
                    "• Work from our Delhi NCR office with flexible hours",
                ].join("\n"),
                requirements: ["React Native", "JavaScript", "REST APIs", "Publishing apps to Play Store / App Store"],
                salary: "10-14 LPA",
                location: "Delhi NCR",
                jobType: "Contract",
                experienceLevel: "Junior",
                position: 1,
            },
            {
                title: "QA Automation Engineer",
                description: [
                    "TechNova Solutions is hiring a part-time QA Automation Engineer (around 20 hours a week) to write automated tests for our web apps and help keep every release bug-free.",
                    "",
                    "What you'll do:",
                    "• Write and maintain automated end-to-end tests with Selenium or Playwright",
                    "• Test new features by hand before each release",
                    "• Report bugs clearly, with the steps needed to reproduce them",
                    "• Work with developers to make sure bugs are fixed and tested again",
                    "• Help improve our testing process and checklists",
                    "",
                    "What we offer:",
                    "• Flexible part-time hours that fit around your schedule",
                    "• Hourly pay based on experience",
                    "• Learning support for test automation tools",
                    "• Chance to move to a full-time role",
                ].join("\n"),
                requirements: ["Selenium or Playwright", "JavaScript", "Manual testing basics", "Bug reporting"],
                salary: "5-7 LPA",
                location: "Chennai",
                jobType: "Part Time",
                experienceLevel: "Junior",
                position: 1,
            },
        ],
    },
    {
        user: {
            fullname: "Rohan Mehta",
            email: "rohan.hr@example.com",
            phoneNumber: 9123456780,
        },
        company: {
            name: "CloudPeak Systems",
            description: "A cloud, data and AI company helping businesses scale their software.",
            website: "https://cloudpeak.example.com",
            location: "Hyderabad",
        },
        jobs: [
            {
                title: "DevOps Engineer",
                description: [
                    "CloudPeak Systems is looking for a DevOps Engineer to build and maintain CI/CD pipelines and cloud infrastructure on AWS. You will help our development teams ship code faster and more safely.",
                    "",
                    "What you'll do:",
                    "• Build and improve CI/CD pipelines with GitHub Actions or Jenkins",
                    "• Run and scale apps with Docker and Kubernetes on AWS",
                    "• Automate infrastructure setup and routine server tasks",
                    "• Set up logging, monitoring and alerts for our services",
                    "• Help developers fix build and deployment problems",
                    "",
                    "What we offer:",
                    "• Competitive salary and a yearly bonus",
                    "• Health insurance for you and your family",
                    "• Paid AWS and Kubernetes certifications",
                    "• Hybrid work from our Hyderabad office",
                ].join("\n"),
                requirements: ["AWS", "Docker", "Kubernetes", "CI/CD (GitHub Actions or Jenkins)", "Linux"],
                salary: "18-26 LPA",
                location: "Hyderabad",
                jobType: "Full Time",
                experienceLevel: "Mid-Level",
                position: 2,
            },
            {
                title: "Senior DevOps / SRE Engineer",
                description: [
                    "We are hiring a Senior DevOps / SRE Engineer to keep the CloudPeak platform reliable and fast. You will own monitoring, alerts and incident response, and lead our work on uptime and performance. This is a fully remote role.",
                    "",
                    "What you'll do:",
                    "• Own the reliability of our production systems and set uptime goals",
                    "• Manage infrastructure as code with Terraform",
                    "• Build dashboards and alerts with Prometheus and Grafana",
                    "• Lead incident response and write clear reports after each incident",
                    "• Mentor DevOps engineers and improve our on-call process",
                    "",
                    "What we offer:",
                    "• Top-of-market salary and stock options",
                    "• Fully remote work with a home-office budget",
                    "• Health insurance and a wellness allowance",
                    "• Extra pay for on-call weeks",
                ].join("\n"),
                requirements: ["Kubernetes", "Terraform", "Prometheus and Grafana", "On-call experience", "5+ years in DevOps"],
                salary: "30-40 LPA",
                location: "Remote",
                jobType: "Full Time",
                experienceLevel: "Senior",
                position: 1,
            },
            {
                title: "Data Scientist",
                description: [
                    "CloudPeak Systems is looking for a Data Scientist to use data science and statistics to find insights and build prediction models for our clients in retail, finance and healthcare.",
                    "",
                    "What you'll do:",
                    "• Clean, explore and analyze large datasets with Python, Pandas and SQL",
                    "• Build and test prediction models, such as sales forecasts and customer churn",
                    "• Explain your findings to clients with clear charts and reports",
                    "• Work with engineers to put your models into production",
                    "• Keep up with new methods and tools in data science",
                    "",
                    "What we offer:",
                    "• Competitive salary and a yearly bonus",
                    "• Health insurance",
                    "• Access to powerful cloud computing for your experiments",
                    "• Learning budget for courses and conferences",
                ].join("\n"),
                requirements: ["Python", "Pandas", "SQL", "Statistics", "Data visualization"],
                salary: "18-25 LPA",
                location: "Hyderabad",
                jobType: "Full Time",
                experienceLevel: "Mid-Level",
                position: 2,
            },
            {
                title: "Data Science Intern",
                description: [
                    "Learn data science on real projects with a 6-month internship at our Pune office. You will clean data, build charts and create simple models while working with experienced data scientists.",
                    "",
                    "What you'll do:",
                    "• Clean and prepare data with Python and Excel or SQL",
                    "• Build charts and dashboards that explain what the data shows",
                    "• Help train and test simple machine learning models",
                    "• Present your work to the team at the end of each project",
                    "",
                    "What we offer:",
                    "• Monthly stipend",
                    "• A mentor to guide you through every project",
                    "• Internship certificate and a letter of recommendation",
                    "• Chance of a full-time offer based on performance",
                ].join("\n"),
                requirements: ["Python basics", "Excel or SQL", "Interest in data science"],
                salary: "3-5 LPA",
                location: "Pune",
                jobType: "Internship",
                experienceLevel: "Fresher",
                position: 4,
            },
            {
                title: "Machine Learning Engineer",
                description: [
                    "We are hiring a Machine Learning Engineer to train, deploy and monitor ML / AI models in production for search and recommendations. Your models will be used by millions of people across our clients' apps.",
                    "",
                    "What you'll do:",
                    "• Design, train and improve models with PyTorch or TensorFlow",
                    "• Build pipelines to deploy and update models in production",
                    "• Monitor model quality and fix problems such as data drift",
                    "• Make models faster and cheaper to run at scale",
                    "• Guide other engineers on machine learning best practices",
                    "",
                    "What we offer:",
                    "• Top-of-market salary and stock options",
                    "• Health insurance for you and your family",
                    "• Access to GPUs for training and research",
                    "• Budget to attend ML / AI conferences",
                ].join("\n"),
                requirements: ["Python", "PyTorch or TensorFlow", "MLOps", "Model deployment", "5+ years experience"],
                salary: "28-40 LPA",
                location: "Bangalore",
                jobType: "Full Time",
                experienceLevel: "Senior",
                position: 2,
            },
            {
                title: "AI Engineer (LLM Applications)",
                description: [
                    "CloudPeak Systems is looking for a freelance AI Engineer to build ML / AI features with large language models, such as chatbots and document search, for our clients. Work fully remote on your own schedule.",
                    "",
                    "What you'll do:",
                    "• Build chatbots and AI assistants using LLM APIs",
                    "• Create document search with embeddings and vector databases",
                    "• Write and test prompts to get accurate, reliable answers",
                    "• Build backend APIs for these features with Python and FastAPI",
                    "• Share progress with the client team every week",
                    "",
                    "What we offer:",
                    "• Project-based pay with clear milestones",
                    "• Fully remote work and flexible hours",
                    "• Long-term work on new client projects",
                ].join("\n"),
                requirements: ["Python", "LLM APIs", "Prompt engineering", "Vector databases", "FastAPI"],
                salary: "15-20 LPA",
                location: "Remote",
                jobType: "Freelance",
                experienceLevel: "Mid-Level",
                position: 1,
            },
            {
                title: "Database Administrator (MongoDB)",
                description: [
                    "We are looking for a Database Administrator to manage, back up and tune our MongoDB and PostgreSQL databases. You will make sure our data is safe, fast and always available.",
                    "",
                    "What you'll do:",
                    "• Set up, manage and upgrade MongoDB and PostgreSQL databases",
                    "• Plan and test regular backups and recovery",
                    "• Find slow queries and speed them up with better indexes",
                    "• Monitor database health, storage and security",
                    "• Help developers design efficient database structures",
                    "",
                    "What we offer:",
                    "• Competitive salary and a yearly bonus",
                    "• Health insurance",
                    "• Paid MongoDB and PostgreSQL certifications",
                    "• Work from our Chennai office with flexible hours",
                ].join("\n"),
                requirements: ["MongoDB", "PostgreSQL", "Backups and recovery", "Query optimization", "Indexing"],
                salary: "14-20 LPA",
                location: "Chennai",
                jobType: "Full Time",
                experienceLevel: "Mid-Level",
                position: 1,
            },
            {
                title: "Backend Developer (Python)",
                description: [
                    "Start your career building backend services and APIs with Python and FastAPI. This role is made for freshers: you will join a supportive team and learn how real backend systems are built and run.",
                    "",
                    "What you'll do:",
                    "• Build simple REST APIs with Python and FastAPI or Django",
                    "• Write SQL queries and work with databases",
                    "• Write tests and fix bugs with help from senior developers",
                    "• Learn Git, code reviews and how apps are deployed",
                    "",
                    "What we offer:",
                    "• A 3-month training program when you join",
                    "• A dedicated mentor",
                    "• Health insurance",
                    "• A clear path to promotion after your first year",
                ].join("\n"),
                requirements: ["Python", "FastAPI or Django", "SQL basics", "Git"],
                salary: "6-8 LPA",
                location: "Delhi NCR",
                jobType: "Full Time",
                experienceLevel: "Fresher",
                position: 3,
            },
        ],
    },
];
